In [1]:
import pandas as pd
import numpy as np
import math

In [2]:
main_df = pd.read_csv('bingo.csv')

In [38]:
want = list(filter(lambda x: "LastName_FirstName" in x or "-Improved" in x, list(main_df)))
memes = main_df[want]
print(memes)

      LastName_FirstName Meet1-Improved Meet2-Improved Meet3-Improved  \
0       Ackerman, Collin           True           True           True
1       Ackerman, Collin           True            NaN            NaN
2       Ackerman, Collin            NaN            NaN            NaN
3       Ackerman, Collin            NaN            NaN            NaN
4       Ackerman, Collin           True           True           True
5       Ackerman, Collin            NaN           True            NaN
6        Ackerman, Kylee           True           True           True
7        Ackerman, Kylee           True            NaN            NaN
8        Ackerman, Kylee            NaN            NaN            NaN
9        Ackerman, Kylee            NaN           True            NaN
10          Akande, Toba           True            NaN            NaN
11          Akande, Toba           True            NaN            NaN
12          Akande, Toba           True            NaN            NaN
13          Akande, Toba            NaN            NaN            NaN
14          Akande, Toba            NaN            NaN           True
15          Akande, Toba            NaN            NaN            NaN
16         Aldrete, Lucy           True            NaN            NaN
17         Aldrete, Lucy            NaN            NaN            NaN
18         Aldrete, Lucy           True            NaN            NaN
19         Aldrete, Lucy            NaN            NaN           True
20         Aldrete, Lucy            NaN            NaN            NaN
21        Allen, Matthew           True            NaN           True
22        Allen, Matthew           True            NaN           True
23        Allen, Matthew           True            NaN           True
24    Badrayani, Akshata           True            NaN            NaN
25    Badrayani, Akshata            NaN            NaN            NaN
26    Badrayani, Akshata           True            NaN           True
27    Badrayani, Akshata           True            NaN            NaN
28    Badrayani, Akshata            NaN            NaN            NaN
29    Badrayani, Akshata            NaN            NaN            NaN
...                  ...            ...            ...            ...
1016      Zhang, Valerie            NaN            NaN            NaN
1017      Zhang, Valerie            NaN           True            NaN
1018      Zhang, Valerie           True            NaN            NaN
1019        Zhang, Aaron           True            NaN            NaN
1020        Zhang, Aaron            NaN            NaN            NaN
1021        Zhang, Aaron           True            NaN            NaN
1022        Zhang, Aaron            NaN           True            NaN
1023        Zhang, Aaron           True           True            NaN
1024        Zhang, Alice            NaN            NaN           True
1025        Zhang, Alice           True           True            NaN
1026        Zhang, Alice           True            NaN            NaN
1027        Zhang, Alice           True           True            NaN
1028        Zhang, Alice            NaN           True           True
1029        Zhang, Isaac           True            NaN            NaN
1030        Zhang, Isaac            NaN            NaN            NaN
1031        Zhang, Isaac           True            NaN            NaN
1032        Zhang, Isaac           True            NaN            NaN
1033        Zhang, Isaac            NaN            NaN            NaN
1034       Zhang, Steven           True            NaN            NaN
1035       Zhang, Steven           True            NaN           True
1036       Zhang, Steven           True            NaN           True
1037       Zhang, Steven            NaN           True           True
1038       Zhang, Steven            NaN           True            NaN
1039       Zhang, Steven            NaN            NaN            NaN
1040      Zhang, Vincent            NaN           True            NaN
1041      Zhang, Vincent           True           True            NaN
1042      Zhang, Vincent           True            NaN            NaN
1043      Zhang, Vincent            NaN            NaN            NaN
1044      Zhang, Vincent            NaN           True            NaN
1045      Zhang, Vincent           True            NaN            NaN

     Meet4-Improved Meet5-Improved Meet6-Improved  Meet7-Improved  \
0               NaN            NaN            NaN             NaN
1              True            NaN            NaN             NaN
2              True            NaN            NaN             NaN
3               NaN           True           True             NaN
4               NaN            NaN            NaN             NaN
5              True            NaN           True             NaN
6              True           True            NaN             NaN
7               NaN            NaN            NaN             NaN
8               NaN            NaN            NaN             NaN
9              True            NaN            NaN             NaN
10              NaN            NaN            NaN             NaN
11              NaN            NaN            NaN             NaN
12              NaN            NaN            NaN             NaN
13             True            NaN            NaN             NaN
14              NaN            NaN            NaN             NaN
15             True            NaN            NaN             NaN
16             True           True           True             NaN
17              NaN            NaN           True             NaN
18             True            NaN            NaN             NaN
19             True           True           True             NaN
20              NaN            NaN            NaN             NaN
21              NaN           True           True             NaN
22              NaN           True            NaN             NaN
23              NaN           True           True             NaN
24              NaN            NaN            NaN             NaN
25              NaN            NaN           True             NaN
26              NaN            NaN            NaN             NaN
27              NaN            NaN            NaN             NaN
28              NaN           True            NaN             NaN
29              NaN           True            NaN             NaN
...             ...            ...            ...             ...
1016            NaN            NaN            NaN             NaN
1017            NaN            NaN            NaN             NaN
1018            NaN            NaN            NaN             NaN
1019            NaN           True            NaN             NaN
1020            NaN            NaN           True             NaN
1021           True            NaN           True             NaN
1022            NaN           True            NaN             NaN
1023           True            NaN           True             NaN
1024            NaN            NaN           True             NaN
1025            NaN           True            NaN             NaN
1026           True            NaN            NaN             NaN
1027           True            NaN            NaN             NaN
1028           True            NaN            NaN             NaN
1029            NaN            NaN            NaN             NaN
1030            NaN            NaN           True             NaN
1031           True            NaN           True             NaN
1032            NaN            NaN           True             NaN
1033            NaN           True            NaN             NaN
1034           True            NaN            NaN             NaN
1035            NaN           True            NaN             NaN
1036            NaN            NaN            NaN             NaN
1037            NaN            NaN            NaN             NaN
1038            NaN            NaN            NaN             NaN
1039           True            NaN            NaN             NaN
1040            NaN            NaN            NaN             NaN
1041            NaN            NaN            NaN             NaN
1042            NaN            NaN           True             NaN
1043            NaN            NaN           True             NaN
1044            NaN            NaN            NaN             NaN
1045            NaN            NaN            NaN             NaN

      Meet8-Improved
0                NaN
1                NaN
2                NaN
3                NaN
4                NaN
5                NaN
6                NaN
7                NaN
8                NaN
9                NaN
10               NaN
11               NaN
12               NaN
13               NaN
14               NaN
15               NaN
16               NaN
17               NaN
18               NaN
19               NaN
20               NaN
21               NaN
22               NaN
23               NaN
24               NaN
25               NaN
26               NaN
27               NaN
28               NaN
29               NaN
...              ...
1016             NaN
1017             NaN
1018             NaN
1019             NaN
1020             NaN
1021             NaN
1022             NaN
1023             NaN
1024             NaN
1025             NaN
1026             NaN
1027             NaN
1028             NaN
1029             NaN
1030             NaN
1031             NaN
1032             NaN
1033             NaN
1034             NaN
1035             NaN
1036             NaN
1037             NaN
1038             NaN
1039             NaN
1040             NaN
1041             NaN
1042             NaN
1043             NaN
1044             NaN
1045             NaN

[1046 rows x 9 columns]

In [3]:
age_df = main_df[['AgeGroup','LastName_FirstName']]
age_df=age_df.set_index('LastName_FirstName')
age_df = age_df[~age_df.index.duplicated(keep='first')]
age_group = age_df['AgeGroup'].tolist()

In [4]:
#Creates targeted dataframe
target_df = main_df[['LastName_FirstName','Meet1-Improved','Meet2-Improved','Meet3-Improved','Meet4-Improved','Meet5-Improved','Meet6-Improved']]
target_df = target_df.set_index('LastName_FirstName')

In [5]:
#Deletes the first instance of true in each row
condition = target_df.cumsum(axis=1) == 1
target_df = target_df.mask(condition, False)

In [6]:
#Creates list of unique names
big_list = target_df.index.unique()

In [7]:
names = [] #Stores Names
bingos = [] #Stores Bingo Score

#Sepereates all of the different names in temp dataframe
for name in big_list:
    temp_df = target_df.copy()
    temp_df = temp_df.loc[temp_df.index == name]
    
    #Counts the number of bingos each swimmer achieved
    score=0
    for column in temp_df:
        x = np.sum(temp_df[column])
       
        if math.isnan(x) is True:
            x=0
        
        if x > 2:
            score = score + 1
    
    names.append(name)
    bingos.append(score)

In [8]:
#Create results dataframe
final_df = pd.DataFrame({'Age Group': age_group,'Name': names,'Bingo Count': bingos})
final_df = final_df.set_index('Name')

In [9]:
final_df.to_csv('final.csv')